on: [push]

name: Linux_Container_Python_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: amlajanazure.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t amlajanazure.azurecr.io/amlajan-docker:${{ github.sha }}
          docker push amlajanazure.azurecr.io/amlajan-docker:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "amlajan"
          images: "amlajanazure.azurecr.io/amlajan-docker:${{ github.sha }}"
