# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - newamlajan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://newamlaja.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_615940f19e274f67b998e58629222ad6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8911c7c89c1946f586a7f312be0bd991 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_615940f19e274f67b998e58629222ad6 }}/amlajan-docker:latest
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'newamlajan'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_771aa87bbb804439aa7fd27e965dd986 }}
        images: 'newamlaja.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_615940f19e274f67b998e58629222ad6 }}/amlajan-docker:latest'
