# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - amlajan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://amlajanazure.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0b574b04793648588e4c02f071a28234 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_144536ceb86645669f6bcbf747281980 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_0b574b04793648588e4c02f071a28234 }}/amlajan-docker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'amlajan'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a9387d966b4541ccb07b31d2c265cb48 }}
        images: 'amlajanazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0b574b04793648588e4c02f071a28234 }}/amlajan-docker:${{ github.sha }}'